name: Gradle Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 1'  # tous les lundis à minuit UTC

jobs:
  build:
    name: Build Insights on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'

    - name: Grant execute permission to script
      run: bash -c "chmod +x script.sh"
    - name: Update upstream and apply patches
      shell: bash
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Action Github"
        ./script.sh updateUpstream
        ./script.sh applyPatches

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ !(github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/version/')) }}

    - name: Execute Gradle build
      run: |
        cd Insights-Patchs
        ./gradlew build --stacktrace

    - uses: actions/upload-artifact@v4
      name: Archive Reports
      if: always()
      with:
        name: reports for ${{ matrix.os }}
        path: 'Insights-Patchs/build/reports/**'

    - uses: actions/upload-artifact@v4
      name: Archive Logs
      if: always()
      with:
        name: logs for ${{ matrix.os }}
        path: 'Insights-Patchs/*.log'

    - name: Upload Insights jar
      uses: actions/upload-artifact@v4
      with:
        name: Insights-Folia-Snapshot
        path: Insights-Patchs/jars/*
